sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.4.2"
      env: TOXENV=py34
    - python: "3.4.2"
      env: TOXENV=lint

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
language: python
script: tox
